---
version: 1
update_configs:
- package_manager: "java:gradle"
  directory: "/examples/multi-redis-cache-failure-handling"
  update_schedule: "daily"
- package_manager: "java:gradle"
  directory: "/examples/redis-cache-failure-handling"
  update_schedule: "daily"
